# Generated by Django 3.2.9 on 2022-11-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_auto_20221031_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя заявителя')),
                ('phone', models.CharField(default='+7', help_text='Ввод номера в формате 8 999 999 99 99', max_length=12, verbose_name='Телефон заявителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата заявки')),
            ],
        ),
    ]
