# Generated by Django 3.2.9 on 2022-11-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_alter_product_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='f_chislo_stupeney',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='f_garantiya',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='f_krav_v_korobke',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='f_max_bar',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='f_min_bar',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='f_nasos',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='f_proizviditelnost',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='f_razmer',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='f_resurs',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='f_short_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='f_type_voda',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='k_garantiya',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='k_max_mosch',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='k_max_temp_contura',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='k_max_temp_gvs',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='k_min_mosch',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='k_min_temp_gvs',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='k_nomimal_podacha_gaza',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='k_norma_jj_gas',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='k_norma_prirod_gas',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='k_obem_baka',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='k_pritok_pri_at25',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='k_proizvoditel',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='k_short_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='k_trebuemaya_mosch',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
